services:
    php:
        build: docker
        user: 1000:1000
        ports:
            - "80:80"
            - "443:443"
            - "443:443/udp"
        volumes:
            - ./:/app
            - caddy_data:/data
            - caddy_config:/config
        # commentez la ligne suivante en production, elle permet d'avoir de beaux logs lisibles en dev
        tty: true
        depends_on: [ postgres ]
        restart: unless-stopped

    postgres:
        image: postgres:16
        volumes:
            - postgres:/data/postgres
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: skank-jukebox
            POSTGRES_PASSWORD: changeme
            PGDATA: /data/postgres
        restart: unless-stopped

volumes:
    caddy_data:
    caddy_config:
    postgres:
